// Mapeo de estados a clases de Bootstrap
export const STATUS_MAP = {
  'Activo':      'success',
  'Inactivo':    'secondary',
  'Vigente':     'success',
  'Vencido':     'danger',
  'Disponible':  'success',
  'Mantenimiento': 'warning',
  'Pendiente':   'warning',
  'Pagada':      'success',
  'Vencida':     'danger',
  'Abierta':     'danger',
  'En proceso':  'warning',
  'Resuelta':    'success',
  'Alta':        'danger',
  'Media':       'warning',
  'Baja':        'secondary',
  'Aplicado':    'success',
}

// Etiquetas legibles para columnas de tabla
export const COL_LABELS = {
  id:            '#',
  nombre:        'Nombre',
  descripcion:   'Descripción',
  estado:        'Estado',
  tipo:          'Tipo',
  unidad:        'Unidad',
  telefono:      'Teléfono',
  residente:     'Residente',
  propiedad:     'Propiedad',
  inicio:        'Inicio',
  fin:           'Fin',
  monto:         'Monto',
  persona:       'Persona',
  entrada:       'Entrada',
  salida:        'Salida',
  fecha:         'Fecha',
  no:            'No.',
  concepto:      'Concepto',
  metodo:        'Método',
  capacidad:     'Capacidad',
  tarifa:        'Tarifa',
  cargo:         'Cargo',
  turno:         'Turno',
  titulo:        'Título',
  categoria:     'Categoría',
  prioridad:     'Prioridad',
  reportado:     'Reportado',
  usuario:       'Usuario',
  rol:           'Rol',
  ultimo_acceso: 'Último Acceso',
  factura:       'Factura',
}
